project:
  type: website

website:
  title: "Mykel Brinkerhoff's Blog"
  site-url: https://blog.mlbrinkerhoff.me
  description: "A blog about linguistics, programming, and other things."
  google-analytics: "G-MW6LP1WSCZ"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - icon: rss
        href: index.xml
format:
  html:
    theme:
      - sandstone
      - brand
    css: styles.css
    code-overflow: wrap
    code-line-numbers: true
    toc: true
    toc-depth: 2
    toc-location: left